### ISSUE TITLE
CRUD operations

### ISSUE THREAD

**Issue by spencerthayer** [jas-/crypt.io#10]
In issue https://github.com/jas-/crypt.io/issues/7 there is a discussion about updating and deleting entries. While it focused on an issue with outdated dependencies the main question did not seem resolved. (_Or maybe I just read it too fast?_)

Anyway, to clarify: **Does Crypt.io have a full CRUD cycle built in? If so is there documentation for this?**

Thank you!

**Comment by jas-** [comment]
No it doesn't. Setting and getting are the only two methods.

**Comment by spencerthayer** [comment]
I'm trying to retreive all the encrypted keys but when the `encryptPassword` doesn't match it kills the function with `uncaught exception: CORRUPT: ccm: tag doesn't match`.

```javascript
function testValue() {
    cleanStore();
    storage = cryptio;
    for (var i = 0, len = localStorage.length; i < len; ++i) {
        keyID = localStorage.key(i);
        keyObject = localStorage.getItem(localStorage.key(i));
        console.log(keyID + keyObject);
        // console.log(encryptPassword);
        storage.get({ passphrase: encryptPassword }, keyID, function(err, results) {
            console.log(err);
            console.log(results);
        });
    }
}
testValue();
```

Any idea how I would for loop through all the keys to see which one the `encryptPassword` matches? The idea is that the user could use multiple encryptPassword's for multiple entries in localStorage. Two users can use the same site on the same browser but with different results.

**Comment by jas-** [comment]
This functionality is outside of the scope this module provided

**Comment by spencerthayer** [comment]
Fair enough. I'll likely write something similar to crypt.io but with CRUD then. Thanks.

**Comment by jas-** [comment]
Sounds like you don't want to use the nosql interface available with localStorage and sessionStorage and would prefer to use the indexedDB (since depreciated) to deal with CRUD.

The CCM error you are experiencing needs to be handled in the module but isn't currently

**Comment by jas-** [comment]
@spencerthayer `v1.0.5` should address the CCM errors but I did not test it thoroughly due to my reservations about implementing this as a way to brute force encrypted stored data through a browser extension per domain.

**Comment by spencerthayer** [comment]
NICE! Thank you.

**Comment by jas-** [comment]
Did that resolve your issue?

**Comment by spencerthayer** [comment]
Sorry. I won't be able to look at this until Monday. I'm certain it did though.
