### ISSUE TITLE
retrieving encrypted data

### ISSUE THREAD

**Issue by spencerthayer** [jas-/crypt.io#9]
In your example of user input for the passphrase you don't explain how to retrieve the data once it is encrypted.

```javascript
var storage = cryptio;

storage.get('inventory', function(err, results){
  if (err) throw err;
  console.log(results);
});
```

**Comment by jas-** [comment]
Sure. You can use the 'option' argument to the '.get()' function like so...

'''storage.get({passphrase: 'secret squirrel'}, 'inventory', function(err, data){ ... })'''

**Comment by spencerthayer** [comment]
```xml
<hero>YOU</hero>
```

**Comment by jas-** [comment]
Glad it helped. I will update the docs
